// <auto-generated>
// Code generated by luis:generate:cs
// Tool github: https://github.com/microsoft/botframework-cli
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>
using Newtonsoft.Json;
using Newtonsoft.Json.Serialization;
using System;
using System.Collections.Generic;
using Microsoft.Bot.Builder;
using Microsoft.Bot.Builder.AI.Luis;
namespace Chatbot.CognitiveModels
{
    public partial class SimpleModel: IRecognizerConvert
    {
        [JsonProperty("text")]
        public string Text;

        [JsonProperty("alteredText")]
        public string AlteredText;

        public enum Intent {
            finishedstatement,
            list,
            None,
            searchsubject,
            simplestatement
        };
        [JsonProperty("intents")]
        public Dictionary<Intent, IntentScore> Intents;

        public class _Entities
        {
            // Simple entities
            public string[] around;
            public string[] between;
            public string[] bigger;
            public string[] negate;
            public string[] obj;
            public string[] smaller;
            public string[] subject;

            // Built-in entities
            public DateTimeSpec[] datetime;
            public GeographyV2[] geographyV2;
            public double[] number;
            public string[] personName;


            // Composites
            public class _InstanceValue
            {
                public InstanceData[] date;
                public InstanceData[] personName;
                public InstanceData[] geography;
                public InstanceData[] number;
                public InstanceData[] text;
            }
            public class ValueClass
            {
                public string[] date;
                public string[] personName;
                public string[] geography;
                public double[] number;
                public string[] text;
                [JsonProperty("$instance")]
                public _InstanceValue _instance;
            }
            public ValueClass[] value;

            // Instance
            public class _Instance
            {
                public InstanceData[] around;
                public InstanceData[] between;
                public InstanceData[] bigger;
                public InstanceData[] date;
                public InstanceData[] datetime;
                public InstanceData[] geography;
                public InstanceData[] geographyV2;
                public InstanceData[] negate;
                public InstanceData[] number;
                public InstanceData[] obj;
                public InstanceData[] personName;
                public InstanceData[] smaller;
                public InstanceData[] subject;
                public InstanceData[] text;
                public InstanceData[] value;
            }
            [JsonProperty("$instance")]
            public _Instance _instance;
        }
        [JsonProperty("entities")]
        public _Entities Entities;

        [JsonExtensionData(ReadData = true, WriteData = true)]
        public IDictionary<string, object> Properties {get; set; }

        public void Convert(dynamic result)
        {
            var app = JsonConvert.DeserializeObject<SimpleModel>(
                JsonConvert.SerializeObject(
                    result,
                    new JsonSerializerSettings { NullValueHandling = NullValueHandling.Ignore, Error = OnError }
                )
            );
            Text = app.Text;
            AlteredText = app.AlteredText;
            Intents = app.Intents;
            Entities = app.Entities;
            Properties = app.Properties;
        }

        private static void OnError(object sender, ErrorEventArgs args)
        {
            // If needed, put your custom error logic here
            Console.WriteLine(args.ErrorContext.Error.Message);
            args.ErrorContext.Handled = true;
        }

        public (Intent intent, double score) TopIntent()
        {
            Intent maxIntent = Intent.None;
            var max = 0.0;
            foreach (var entry in Intents)
            {
                if (entry.Value.Score > max)
                {
                    maxIntent = entry.Key;
                    max = entry.Value.Score.Value;
                }
            }
            return (maxIntent, max);
        }
    }
}
